### ISSUE TITLE
Please update IRTV

### ISSUE THREAD

**Issue by BulletBates17** [Gamergotten/Infinite-runtime-tagviewer#141] opened 2024-03-09 19:27 UTC
Please update IRTV
IRTV closes when  i launch it and many people have the same problem and even the one where they tall back in forth on ho wto fix it and i tried it and it did not work so please update and fix it

**Comment by Connor-jt** [comment] 2024-03-09 22:06
we cant update IRTV if we do not know what the issue is, and it sounds more like user error than something on our end

try following some of the suggestions from #133 (just click on the '133' to follow the link)
let us know what does or doesn't work

also, i'd recommend checking the windows event viewer so you can share why the program is actually crashing

to do that, search 'event viewer' into your windows search bar and open the app, then in the app double click on 'Windows Logs' on the left side panel, then double click 'application' and then you should beable to find the IRTV crash event
if you dont see the IRTV crash information, try reopening IRTV and refresh the event viewer

**Comment by Connor-jt** [comment] 2024-03-09 22:07
also, you already have an open issue on the same topic, it would be preferable if you stopped creating new issues

**Comment by Gamergotten** [comment] 2024-03-14 04:06
Closing as it seems the poster is not willing to elaborate any further, and thus the issue cannot be confirmed as something on our end.

**Closed as completed by Gamergotten** 2024-03-14 04:06 UTC

**Comment by Gamergotten** [comment] 2024-03-14 04:08
Feel free to reopen this issue if you do happen to have anything else to add that would be useful in allowing us to understand your problem.
Otherwise we have to assume this is a result of some user error.
