### ISSUE TITLE
IRTV not launching

### ISSUE THREAD

**Issue by BulletBates17** [Gamergotten/Infinite-runtime-tagviewer#134] opened 2023-12-28 19:29 UTC
When I try to launch IRTV it opens the, do you want to allow this app to change your settings, when I press yes it closes it and never opens IRTV. With the new season 5 version installed and all older versions don't work.

**Comment by Sopitive** [comment] 2023-12-28 20:43
Duplicate of #133 

note from maintainer: Unconfirmed

**Comment by Gamergotten** [comment] 2024-03-14 04:01
closed because an issue of the same nature was opened from the same user

**Closed as completed by Gamergotten** 2024-03-14 04:01 UTC
